# Generated by Django 5.1 on 2024-11-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='financas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Renda')),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Despesas')),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Lucro')),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Meta')),
                ('meses', models.IntegerField(default=12, verbose_name='Meses')),
            ],
        ),
    ]
